auth:
  rest:
    port: 8080
    url: http://localhost:8080
  grpc:
    url: 0.0.0.0:5005
    port: 5005
  graphql:
    url: /api/v1/auth/graphql
inventory:
  rest:
    port: 8081
    url: http://localhost:8081
  grpc:
    url: 0.0.0.0:5006
  graphql:
    url: /api/v1/inventory/graphql
user:
  rest:
    port: 8082
    url: http://localhost:8082
  grpc:
    url: 0.0.0.0:5003
  graphql:
    url: /api/v1/user/graphql
