// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: auth/auth.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthGrpcService_CreateSubUser_FullMethodName  = "/AuthGrpcService/createSubUser"
	AuthGrpcService_RevokeSubUser_FullMethodName  = "/AuthGrpcService/revokeSubUser"
	AuthGrpcService_RemoveSubUser_FullMethodName  = "/AuthGrpcService/removeSubUser"
	AuthGrpcService_UpdateRoleUser_FullMethodName = "/AuthGrpcService/updateRoleUser"
	AuthGrpcService_GetPermission_FullMethodName  = "/AuthGrpcService/getPermission"
)

// AuthGrpcServiceClient is the client API for AuthGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthGrpcServiceClient interface {
	CreateSubUser(ctx context.Context, in *CreateSubUserRequest, opts ...grpc.CallOption) (*CreateSubUserResponse, error)
	RevokeSubUser(ctx context.Context, in *RevokeSubUserRequest, opts ...grpc.CallOption) (*CreateSubUserResponse, error)
	RemoveSubUser(ctx context.Context, in *RemoveSubUserRequest, opts ...grpc.CallOption) (*CreateSubUserResponse, error)
	UpdateRoleUser(ctx context.Context, in *UpdateRoleUserRequest, opts ...grpc.CallOption) (*CreateSubUserResponse, error)
	GetPermission(ctx context.Context, in *GetPermissionrRequest, opts ...grpc.CallOption) (*GetPermissionResponse, error)
}

type authGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthGrpcServiceClient(cc grpc.ClientConnInterface) AuthGrpcServiceClient {
	return &authGrpcServiceClient{cc}
}

func (c *authGrpcServiceClient) CreateSubUser(ctx context.Context, in *CreateSubUserRequest, opts ...grpc.CallOption) (*CreateSubUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubUserResponse)
	err := c.cc.Invoke(ctx, AuthGrpcService_CreateSubUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authGrpcServiceClient) RevokeSubUser(ctx context.Context, in *RevokeSubUserRequest, opts ...grpc.CallOption) (*CreateSubUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubUserResponse)
	err := c.cc.Invoke(ctx, AuthGrpcService_RevokeSubUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authGrpcServiceClient) RemoveSubUser(ctx context.Context, in *RemoveSubUserRequest, opts ...grpc.CallOption) (*CreateSubUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubUserResponse)
	err := c.cc.Invoke(ctx, AuthGrpcService_RemoveSubUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authGrpcServiceClient) UpdateRoleUser(ctx context.Context, in *UpdateRoleUserRequest, opts ...grpc.CallOption) (*CreateSubUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubUserResponse)
	err := c.cc.Invoke(ctx, AuthGrpcService_UpdateRoleUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authGrpcServiceClient) GetPermission(ctx context.Context, in *GetPermissionrRequest, opts ...grpc.CallOption) (*GetPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPermissionResponse)
	err := c.cc.Invoke(ctx, AuthGrpcService_GetPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthGrpcServiceServer is the server API for AuthGrpcService service.
// All implementations must embed UnimplementedAuthGrpcServiceServer
// for forward compatibility.
type AuthGrpcServiceServer interface {
	CreateSubUser(context.Context, *CreateSubUserRequest) (*CreateSubUserResponse, error)
	RevokeSubUser(context.Context, *RevokeSubUserRequest) (*CreateSubUserResponse, error)
	RemoveSubUser(context.Context, *RemoveSubUserRequest) (*CreateSubUserResponse, error)
	UpdateRoleUser(context.Context, *UpdateRoleUserRequest) (*CreateSubUserResponse, error)
	GetPermission(context.Context, *GetPermissionrRequest) (*GetPermissionResponse, error)
	mustEmbedUnimplementedAuthGrpcServiceServer()
}

// UnimplementedAuthGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthGrpcServiceServer struct{}

func (UnimplementedAuthGrpcServiceServer) CreateSubUser(context.Context, *CreateSubUserRequest) (*CreateSubUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubUser not implemented")
}
func (UnimplementedAuthGrpcServiceServer) RevokeSubUser(context.Context, *RevokeSubUserRequest) (*CreateSubUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeSubUser not implemented")
}
func (UnimplementedAuthGrpcServiceServer) RemoveSubUser(context.Context, *RemoveSubUserRequest) (*CreateSubUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSubUser not implemented")
}
func (UnimplementedAuthGrpcServiceServer) UpdateRoleUser(context.Context, *UpdateRoleUserRequest) (*CreateSubUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoleUser not implemented")
}
func (UnimplementedAuthGrpcServiceServer) GetPermission(context.Context, *GetPermissionrRequest) (*GetPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPermission not implemented")
}
func (UnimplementedAuthGrpcServiceServer) mustEmbedUnimplementedAuthGrpcServiceServer() {}
func (UnimplementedAuthGrpcServiceServer) testEmbeddedByValue()                         {}

// UnsafeAuthGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthGrpcServiceServer will
// result in compilation errors.
type UnsafeAuthGrpcServiceServer interface {
	mustEmbedUnimplementedAuthGrpcServiceServer()
}

func RegisterAuthGrpcServiceServer(s grpc.ServiceRegistrar, srv AuthGrpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthGrpcService_ServiceDesc, srv)
}

func _AuthGrpcService_CreateSubUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServiceServer).CreateSubUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthGrpcService_CreateSubUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServiceServer).CreateSubUser(ctx, req.(*CreateSubUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthGrpcService_RevokeSubUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeSubUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServiceServer).RevokeSubUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthGrpcService_RevokeSubUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServiceServer).RevokeSubUser(ctx, req.(*RevokeSubUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthGrpcService_RemoveSubUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSubUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServiceServer).RemoveSubUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthGrpcService_RemoveSubUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServiceServer).RemoveSubUser(ctx, req.(*RemoveSubUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthGrpcService_UpdateRoleUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServiceServer).UpdateRoleUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthGrpcService_UpdateRoleUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServiceServer).UpdateRoleUser(ctx, req.(*UpdateRoleUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthGrpcService_GetPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServiceServer).GetPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthGrpcService_GetPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServiceServer).GetPermission(ctx, req.(*GetPermissionrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthGrpcService_ServiceDesc is the grpc.ServiceDesc for AuthGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuthGrpcService",
	HandlerType: (*AuthGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createSubUser",
			Handler:    _AuthGrpcService_CreateSubUser_Handler,
		},
		{
			MethodName: "revokeSubUser",
			Handler:    _AuthGrpcService_RevokeSubUser_Handler,
		},
		{
			MethodName: "removeSubUser",
			Handler:    _AuthGrpcService_RemoveSubUser_Handler,
		},
		{
			MethodName: "updateRoleUser",
			Handler:    _AuthGrpcService_UpdateRoleUser_Handler,
		},
		{
			MethodName: "getPermission",
			Handler:    _AuthGrpcService_GetPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
