package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"core/app/helper"
	oAuthService "march-auth/cmd/app/services/oAuth"
)

// OAuthURL is the resolver for the oAuthUrl field.
func (r *mutationResolver) OAuthURL(ctx context.Context) (*string, error) {
	logctx := helper.LogContext("OAuthURLResolvers", "OAuthURL")
	logctx.Logger([]interface{}{}, "")
	return oAuthService.OAuthURL()
	// panic(fmt.Errorf("not implemented: OAuthURL - oAuthUrl"))
}
