// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

type Address struct {
	ID          *string `json:"id,omitempty"`
	Address     *string `json:"address,omitempty"`
	HouseNo     *string `json:"houseNo,omitempty"`
	Moo         *string `json:"moo,omitempty"`
	Soi         *string `json:"soi,omitempty"`
	Road        *string `json:"road,omitempty"`
	District    *string `json:"district,omitempty"`
	SubDistrict *string `json:"subDistrict,omitempty"`
	Province    *string `json:"Province,omitempty"`
	ZipCode     *string `json:"zipCode,omitempty"`
	CreatedBy   *string `json:"createdBy,omitempty"`
	UpdatedBy   *string `json:"updatedBy,omitempty"`
	UpdatedAt   *string `json:"updatedAt,omitempty"`
	CreatedAt   *string `json:"createdAt,omitempty"`
}

type Function struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type GetPermission struct {
	Shop      *Shop       `json:"shop"`
	Functions []*Function `json:"functions"`
	Tasks     []*Task     `json:"tasks"`
}

type GetPermissionResponse struct {
	Data   *GetPermission `json:"data,omitempty"`
	Status *Status        `json:"status,omitempty"`
}

type Group struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	ShopsID        string           `json:"shopsId"`
	GroupFunctions []*GroupFunction `json:"groupFunctions"`
	GroupTasks     []*GroupTask     `json:"groupTasks"`
}

type GroupFunction struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	FunctionID string `json:"functionId"`
	GroupID    string `json:"groupId"`
	Create     bool   `json:"create"`
	View       bool   `json:"view"`
	Update     bool   `json:"update"`
}

type GroupTask struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	GroupID   string `json:"groupId"`
	TaskID    string `json:"taskId"`
	ShopsID   string `json:"shopsId"`
	CreatedBy string `json:"createdBy"`
	UpdatedBy string `json:"updatedBy"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Mutation struct {
}

type ParamsCreateSubUser struct {
	Role        string  `json:"role"`
	Email       string  `json:"email"`
	Firstname   string  `json:"firstname"`
	Lastname    string  `json:"lastname"`
	Description *string `json:"description,omitempty"`
}

type ParamsUpdateRoleUser struct {
	UserID string `json:"userId"`
	Role   string `json:"role"`
}

type Query struct {
}

type Shop struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	CreatedBy   string   `json:"createdBy"`
	UpdatedBy   string   `json:"updatedBy"`
	CreatedAt   string   `json:"createdAt"`
	UpdatedAt   string   `json:"updatedAt"`
	Groups      []*Group `json:"groups"`
	Users       []*User  `json:"users"`
}

type Status struct {
	Code    int     `json:"code"`
	Message *string `json:"message,omitempty"`
}

type SubUserData struct {
	ID *string `json:"id,omitempty"`
}

type SubUserDataResponse struct {
	Data   *User   `json:"data,omitempty"`
	Status *Status `json:"status,omitempty"`
}

type Task struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	FunctionID  string `json:"functionId"`
	Description string `json:"description"`
}

type User struct {
	ID           *string  `json:"id,omitempty"`
	Username     *string  `json:"username,omitempty"`
	Email        *string  `json:"email,omitempty"`
	CitizenID    *string  `json:"citizenId,omitempty"`
	FirstName    *string  `json:"firstName,omitempty"`
	LastName     *string  `json:"lastName,omitempty"`
	Address      *Address `json:"address,omitempty"`
	Tel          *string  `json:"tel,omitempty"`
	Role         string   `json:"role"`
	ShopsID      string   `json:"shopsId"`
	IsSuperAdmin bool     `json:"isSuperAdmin"`
	IsRegistered bool     `json:"isRegistered"`
	Picture      *string  `json:"picture,omitempty"`
	CreatedBy    *string  `json:"createdBy,omitempty"`
	UpdatedBy    *string  `json:"updatedBy,omitempty"`
	UpdatedAt    *string  `json:"updatedAt,omitempty"`
	CreatedAt    *string  `json:"createdAt,omitempty"`
}
